version: '3.1'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rateflix
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db:
